apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: yacd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ yacd_host }}
    http:
      paths:
      - backend:
          service:
            name: yacd
            port:
              number: 80
        path: /
        pathType: Prefix
