apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: plantuml-server
  labels:
    app: plantuml-server
spec:
  type: ClusterIP
  selector:
    app: plantuml-server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
