apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: clash
  labels:
    app: clash
spec:
  type: NodePort
  selector:
    app: clash
  ports:
    - port: {{ socks5_port }}
      targetPort: {{ socks5_port }}
      nodePort: {{ socks5_node_port }}
      protocol: TCP
      name: socks5
    - port: {{ http_port }}
      targetPort: {{ http_port }}
      nodePort: {{ http_node_port }}
      protocol: TCP
      name: http
    - port: {{ control_port }}
      targetPort: {{ control_port }}
      nodePort: {{ control_node_port }}
      protocol: TCP
      name: control
