apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: yacd
  labels:
    app: yacd
spec:
  type: ClusterIP
  selector:
    app: yacd
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: web
