apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ namespace }}
  name: plantuml-server
spec:
  ingressClassName: traefik
  rules:
    - host: {{ server_host }}
      http:
        paths:
          - backend:
              service:
                name: plantuml-server
                port:
                  number: 8080
            path: /
            pathType: Prefix
