apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: languagetool
  labels:
    app: languagetool
spec:
  type: ClusterIP
  selector:
    app: languagetool
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      name: web
